import { FileText, TrendingUp } from "lucide-react";
import PageHero from "../../components/PageHero";
import DownloadableLibrary from "../../components/DownloadableLibrary";
import { getDownloadableResources } from "../../lib/downloadableResources";
import s from "../../components/components.module.css";

export const dynamic="force-dynamic";
export const metadata={title:"Downloadable Resources",description:"Market analysis, investor guides and practical property resources from PropWealth."};
export default async function Reports(){const resources=await getDownloadableResources();return <div className={s.home}><PageHero eyebrow="Downloadable resources" title="Practical guides for better property decisions.">Download a clear, useful resource when you need it—and use it to make your next property decision with more confidence.</PageHero><section className={s.section}><div className={s.wrap}><div className={s.heading}><div><span className={s.kicker}>PropWealth resource library</span><h2>Research you can <em>put to work.</em></h2></div><p>Each guide is prepared to make a part of the property journey easier to understand.</p></div>{resources.length?<DownloadableLibrary resources={resources}/>:<div className={s.empty}><FileText/><h3>New downloadable guides are coming soon.</h3><p>Our next market reports and investor resources are being prepared.</p></div>}</div></section><section className={s.softSection}><div className={s.wrap}><div className={s.nextPanel}><div><span className={s.kicker}>Research and guidance</span><h2>Want context behind<br/><em>the guide?</em></h2><p>PropWealth Next combines expert consultation, suburb intelligence and organised reports to help you move from information to a practical next step.</p></div><div className={s.research}><FileText size={30}/><h3>Insight made useful.</h3><p>Use local context, market movement and organised research to support your decision.</p><TrendingUp size={22}/></div></div></div></section></div>}
