"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { Plus, Save, Star, Trash2, Upload, X } from "lucide-react";

const blank = { name:"", photo:"", rating:5, postedAt:"", comment:"", source:"Google", visible:true, order:0 };
export default function ReviewManager() {
  const [reviews, setReviews] = useState([]), [editing, setEditing] = useState(null), [saving, setSaving] = useState(false);
  const request = async (url, method="GET", body) => { const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined}); const data=await response.json(); if(!response.ok) throw new Error(data.error||"Request failed"); return data; };
  useEffect(() => { request("/api/admin/reviews").then(setReviews).catch(error => alert(error.message)); }, []);
  const upload = async files => { if(!files?.[0]) return; const form=new FormData(); form.append("files",files[0]); const response=await fetch("/api/admin/upload",{method:"POST",body:form}); const data=await response.json(); if(!response.ok) return alert(data.error||"Upload failed"); setEditing(current=>({...current,photo:data.media.find(item=>item.type==="image")?.url||current.photo})); };
  const save = async event => { event.preventDefault(); setSaving(true); try { const item=await request("/api/admin/reviews",editing._id?"PATCH":"POST",editing._id?{id:editing._id,...editing}:editing); setReviews(list=>editing._id?list.map(review=>review._id===item._id?item:review):[item,...list]); setEditing(null); } catch(error) { alert(error.message); } finally { setSaving(false); } };
  const remove = async id => { if(!confirm("Delete this review permanently?")) return; await request("/api/admin/reviews","DELETE",{id}); setReviews(list=>list.filter(review=>review._id!==id)); };
  return <section className="review-manager"><header><div><span className="eyebrow">Website content</span><h1>Client reviews</h1><p>Add verified Google reviews to the homepage. The newest ten visible reviews are displayed automatically.</p></div><button className="button" onClick={()=>setEditing(blank)}><Plus/> Add review</button></header><div className="review-manager-grid">{reviews.map(review=><article key={review._id}><div className="review-manager-card-head">{review.photo?<Image src={review.photo} alt="" width={46} height={46}/>:<span>{review.name.slice(0,1)}</span>}<div><strong>{review.name}</strong><small>{review.postedAt?new Date(review.postedAt).toLocaleDateString("en-AU"):"No date"} · {review.source}</small></div><div>{Array.from({length:review.rating},(_,i)=><Star key={i} size={13} fill="currentColor"/>)}</div></div><p>{review.comment}</p><footer><span>{review.visible===false?"Hidden":"Visible"}</span><button onClick={()=>setEditing({...review,postedAt:review.postedAt?.slice(0,10)||""})}>Edit</button><button onClick={()=>remove(review._id)} aria-label={`Delete ${review.name}`}><Trash2/></button></footer></article>)}</div>{!reviews.length&&!editing&&<p className="review-manager-empty">No client reviews added yet.</p>}{editing&&<div className="modal-backdrop"><form className="property-editor review-editor" onSubmit={save}><button className="modal-close" type="button" onClick={()=>setEditing(null)}><X/></button><span className="eyebrow">Client review</span><h2>{editing._id?"Edit review":"Add review"}</h2><div className="editor-grid"><label>Name<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Posted date<input type="date" value={editing.postedAt?String(editing.postedAt).slice(0,10):""} onChange={e=>setEditing({...editing,postedAt:e.target.value})}/></label><label>Source<input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})}/></label><label>Star rating<select value={editing.rating} onChange={e=>setEditing({...editing,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} stars</option>)}</select></label><label>Display order<input type="number" value={editing.order||0} onChange={e=>setEditing({...editing,order:Number(e.target.value)})}/></label><label className="toggle"><input type="checkbox" checked={editing.visible!==false} onChange={e=>setEditing({...editing,visible:e.target.checked})}/> Visible on website</label><label className="full">Review comment<textarea required value={editing.comment} onChange={e=>setEditing({...editing,comment:e.target.value})}/></label><label className="full upload-field"><Upload/> Reviewer photo<input type="file" accept="image/*" onChange={e=>upload(e.target.files)}/><small>Optional. Upload a reviewer photo only when you have permission to publish it.</small></label></div><button className="button" disabled={saving}><Save/> Save review</button></form></div>}</section>;
}
