import Image from "next/image";
import Link from "next/link";
import { CalendarDays, Clock3, Mic2, Podcast, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { getSessionBySlug } from "../lib/resourceEntries";
import SessionPlayer from "./SessionPlayer";

const date = value => value ? new Date(value).toLocaleDateString("en-AU", { day:"numeric", month:"long", year:"numeric" }) : "On-demand";
const hostsFor = item => item.hosts?.length ? item.hosts : [item.host || item.author].filter(Boolean);
function Person({ person, guest = false }) { if (!person) return null; return <article className={`session-person ${guest ? "guest" : ""}`}>{person.avatar ? <Image src={person.avatar} alt={person.name} width={54} height={54}/> : <span className="session-person-initial"><UserRound size={21}/></span>}<div><small>{guest ? "Guest host" : "Host"}</small><strong>{person.name}</strong>{person.title && <p>{person.title}</p>}</div></article>; }
function Youtube(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12s0-3.5-.45-5.1a2.7 2.7 0 0 0-1.9-1.9C17.1 4.5 12 4.5 12 4.5s-5.1 0-6.65.45a2.7 2.7 0 0 0-1.9 1.9C3 8.5 3 12 3 12s0 3.5.45 5.1a2.7 2.7 0 0 0 1.9 1.9c1.55.45 6.65.45 6.65.45s5.1 0 6.65-.45a2.7 2.7 0 0 0 1.9-1.9C21 15.5 21 12 21 12Z" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="m10 9.3 4.2 2.7-4.2 2.7V9.3Z" fill="currentColor"/></svg>};function SpotifyMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8.5c4.9-1.5 9.6-.9 13.3 1.1M5.8 12c4.1-1.2 8.1-.7 11.1.9M6.7 15.4c3.3-.9 6.3-.5 8.6.7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>};function ApplePodcastMark(){return <Podcast aria-hidden="true"/>}
export default async function SessionDetail({ slug }) { const item = await getSessionBySlug(slug); if (!item) notFound(); const isWebinar = item.type === "webinar", hosts = hostsFor(item); return <article className="session-detail"><header className="shell session-detail-header"><nav className="breadcrumbs"><Link href="/resources">Resources</Link><span>/</span><Link href="/webinars">Webinars & Podcasts</Link></nav><span className="chip">{isWebinar ? "Webinar replay" : "Podcast episode"}</span><h1>{item.title}</h1><p>{item.excerpt}</p><div className="session-detail-meta"><span><CalendarDays size={16}/>{date(item.eventDate || item.publishedAt)}</span>{item.duration && <span><Clock3 size={16}/>{item.duration}</span>}{!isWebinar && <span><Mic2 size={16}/>PropWealth podcast</span>}</div></header><div className="session-player-stage"><div className="session-player-shell"><SessionPlayer title={item.title} youtubeUrl={item.youtubeUrl} videoUrl={item.videoUrl} audioUrl={item.audioUrl} timestamps={item.timestamps || []}/></div></div><div className="shell session-detail-content">{!isWebinar && item.transcript && <section className="session-transcript"><span className="eyebrow">Podcast transcript</span><h2>Read the conversation</h2>{String(item.transcript).split(/\n{2,}/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</section>}<div className="session-people">{hosts.map(person=><Person key={person._id || person.slug || person.name} person={person}/>)}<Person person={item.guestHost} guest/></div><nav className="session-follow" aria-label="Follow PropWealth"><strong>Follow us on</strong><a href="https://www.youtube.com/" aria-label="PropWealth on YouTube"><Youtube/></a><a href="https://open.spotify.com/" aria-label="PropWealth on Spotify"><SpotifyMark/></a><a href="https://podcasts.apple.com/" aria-label="PropWealth on Apple Podcasts"><ApplePodcastMark/></a></nav>{isWebinar && item.content && <div className="session-notes post-content" dangerouslySetInnerHTML={{ __html:item.content }}/>} {item.relatedResources?.length > 0 && <section className="session-related"><div className="section-head"><div><span className="eyebrow">Keep exploring</span><h2>Related sessions</h2></div></div><div className="session-related-grid">{item.relatedResources.map(related => <Link href={`/webinars/${related.slug}`} key={related._id || related.slug}>{related.coverImage && <Image src={related.coverImage} alt="" width={112} height={76}/>}<span><small>{related.type === "podcast" ? "Podcast" : "Webinar"}</small><strong>{related.title}</strong></span></Link>)}</div></section>}</div></article>; }
