"use client";
import { useEffect,useState } from "react";
import { ArrowRight,Check,X } from "lucide-react";

const initial={name:"",email:"",phone:"",website:""};
export default function WelcomeLeadPopup(){
  const [open,setOpen]=useState(false),[form,setForm]=useState(initial),[sending,setSending]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{if(sessionStorage.getItem("propwealth-lead-popup-seen")||localStorage.getItem("propwealth-lead-popup-complete"))return;sessionStorage.setItem("propwealth-lead-popup-seen","1");const timer=setTimeout(()=>setOpen(true),900);return()=>clearTimeout(timer)},[]);
  const close=()=>setOpen(false);const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  const updatePhone=value=>update("phone",value.replace(/\D/g,"").slice(0,9));
  const submit=async event=>{event.preventDefault();setMessage("");if(!/^[2-9]\d{8}$/.test(form.phone)){setMessage("Please enter a valid 9-digit Australian phone number.");return}setSending(true);try{const response=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,phone:`+61${form.phone}`,consent:true,action:"strategy",propertySlug:"website-introduction",propertyTitle:"Website strategy enquiry",source:"website-popup"})});const data=await response.json();if(!response.ok)throw new Error(data.error);localStorage.setItem("propwealth-lead-popup-complete","1");setMessage("Thank you. Our property strategy team will be in touch shortly.")}catch(error){setMessage(error.message||"We could not save your enquiry.")}finally{setSending(false)}};
  if(!open)return null;
  return <div className="modal-backdrop welcome-popup-backdrop" onMouseDown={close}><section className="welcome-lead-popup" role="dialog" aria-modal="true" aria-labelledby="welcome-lead-title" onMouseDown={event=>event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close enquiry form"><X/></button>{message.startsWith("Thank you")?<div className="success-message"><span><Check/></span><h2 id="welcome-lead-title">You’re all set</h2><p>{message}</p><button className="button" onClick={close}>Continue exploring</button></div>:<><span className="eyebrow">Plan your next move</span><h2 id="welcome-lead-title">Book a conversation</h2><p>Leave your contact details and our Australian property team will get in touch.</p><form className="welcome-lead-form compact-lead-form" onSubmit={submit}><label>Full name *<input required autoComplete="name" value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>Email address *<input required type="email" autoComplete="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label className="full phone-field-label">Australian phone number *<span className="au-phone-field"><span className="au-phone-prefix" aria-label="Australia country code"><span aria-hidden="true">🇦🇺</span><strong>+61</strong></span><input required type="tel" inputMode="numeric" autoComplete="tel-national" pattern="[2-9][0-9]{8}" maxLength="9" placeholder="4XX XXX XXX" value={form.phone} onChange={e=>updatePhone(e.target.value)}/></span><small>Australian numbers only · enter 9 digits without the leading 0</small></label><input className="honeypot" tabIndex="-1" autoComplete="off" value={form.website} onChange={e=>update("website",e.target.value)}/>{message&&<p className="form-error full">{message}</p>}<p className="lead-privacy full">By submitting, you agree that PropWealth may securely store these details and contact you about your enquiry.</p><button className="button full" disabled={sending}>{sending?"Submitting…":<>Start the conversation <ArrowRight size={17}/></>}</button></form></>}</section></div>
}
