import mongoose from "mongoose";
const MediaSchema=new mongoose.Schema({url:{type:String,required:true},type:{type:String,enum:["image","video"],required:true},name:String,mime:String,size:Number},{_id:false});
const TimestampSchema=new mongoose.Schema({time:{type:String,required:true},label:{type:String,required:true}},{_id:false});
const ResourceEntrySchema=new mongoose.Schema({type:{type:String,required:true,enum:["news","webinar","podcast"],index:true},title:{type:String,required:true},slug:{type:String,required:true},excerpt:String,content:String,coverImage:String,media:{type:[MediaSchema],default:[]},category:String,tags:{type:[String],default:[]},author:{type:mongoose.Schema.Types.ObjectId,ref:"Author"},host:{type:mongoose.Schema.Types.ObjectId,ref:"Author"},hosts:{type:[{type:mongoose.Schema.Types.ObjectId,ref:"Author"}],default:[]},guestHost:{type:mongoose.Schema.Types.ObjectId,ref:"Author"},relatedResources:{type:[mongoose.Schema.Types.ObjectId],ref:"ResourceEntry",default:[]},timestamps:{type:[TimestampSchema],default:[]},status:{type:String,enum:["draft","scheduled","published","paused"],default:"draft"},scheduledAt:Date,publishedAt:Date,visible:{type:Boolean,default:true},featured:{type:Boolean,default:false},eventDate:Date,duration:String,youtubeUrl:{type:String,trim:true},videoUrl:String,audioUrl:String,transcript:String,guestName:String,guestBio:String,speakers:{type:[String],default:[]},registrationUrl:String,location:String,seoTitle:String,seoDescription:String},{timestamps:true});
ResourceEntrySchema.index({type:1,slug:1},{unique:true});
const ResourceEntry=mongoose.models.ResourceEntry||mongoose.model("ResourceEntry",ResourceEntrySchema);
if(!ResourceEntry.schema.path("youtubeUrl")){ResourceEntry.schema.add({youtubeUrl:{type:String,trim:true}});ResourceEntry.recompileSchema?.()}
if(!ResourceEntry.schema.path("hosts")){ResourceEntry.schema.add({hosts:{type:[{type:mongoose.Schema.Types.ObjectId,ref:"Author"}],default:[]}});ResourceEntry.recompileSchema?.()}
export default ResourceEntry;
